[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "sts-nova-bridge"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
  "aws_sdk_bedrock_runtime>=0.1.0,<0.2.0",
  "smithy-aws-core>=0.0.1",
  "websockets>=15.0,<16.0",
]

[tool.setuptools]
packages = ["nova_bridge"]

